app_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default }
    type:     annotate
app_category:
     path:     /category/
     defaults: { _controller: AppBundle:Category }
     type:     annotate